### ISSUE TITLE
Update README.md to Standard format

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/Guessing-Games#1]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Check out this [link](https://github.com/salman-bhai/E-Manager/blob/master/README.md) to understand better.

**Comment by geekcom** [comment]
Claim...

**Comment by sbshah97** [comment]
Go ahead @geekcom Send in a PR.

**Comment by sbshah97** [comment]
@geekcom Haven't recieved your PR. Issue up-for-grabs before next claim.

**Comment by geekcom** [comment]
i'm fineshed. @salman-bhai

**Comment by geekcom** [comment]
hey @salman-bhai , Use shields with your composer PHP repository, info and stats like how many times your project has been downloaded or its latest stable version, are taken from packagist. https://poser.pugx.org/

**Comment by puranik9** [comment]
Is still still available?

**Comment by sbshah97** [comment]
Yes!

**Comment by puranik9** [comment]
I'm working on it!
