### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/Guessing-Games#2]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Check out this [link](https://github.com/salman-bhai/E-Manager/blob/master/README.md) to understand better.

**Comment by bertelledani** [comment]
claim!

**Comment by richa-coder** [comment]
I claim !!

**Comment by richa-coder** [comment]
I added.

**Comment by sbshah97** [comment]
@richa-coder It was claimed first by @bertelledani so I'll have to give it to her. If she doesn't finish it after 24 hours you're welcome to send a Pull Request.

**Comment by sbshah97** [comment]
@richa-coder Haven't recieved a Pull Request. Go ahead and submit your Pull Request.

**Comment by bertelledani** [comment]
Wasn't that 24 hour? I was sleeping when you said it was okay to send it. :)

**Comment by richa-coder** [comment]
I have already sent.

[image: --]

Richa Singh
[image: https://]about.me/richa-singh
https://about.me/richa-singh?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links

**Comment by SilentFlame** [comment]
Is it done?

**Comment by sbshah97** [comment]
It has been already done!
