### ISSUE TITLE
Add MIT License

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/Guessing-Games#3]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by tejado** [comment]
_claim_ :)

**Comment by sbshah97** [comment]
Go ahead, submit a Pull Request @tejado

**Comment by richa-coder** [comment]
Is the licence added or should i add it??

**Comment by sbshah97** [comment]
The Issue has already been claimed people. If @tejado doesn't send a Pull Request at the end of 24 hours, whoever claims the Issue first can send a Pull Request that will be accepted.

**Comment by tejado** [comment]
Here is the PR: https://github.com/salman-bhai/Guessing-Games/pull/9
Sorry for beeing so late. And thanks for your contributions to hacktoberfest.

**Comment by sbshah97** [comment]
Thank you people for contributing, but kindly read the Repository guidelines first before sending your Pull Requests.
